"""Canonical ``personetta`` launcher shim (PATH-independent invocation).

Used by ``scripts/install-personetta.sh`` to put a ``personetta`` command on PATH
without a PEP-668-blocked ``pip install``. The shim runs an installed package if
one is importable, else the source tree via ``PERSONETTA_BASE/src``. Centralised
here so the installer, the hook wrapper, and tests share one definition.
"""

from __future__ import annotations


def render_launcher_shim(base_dir: str) -> str:
    """Return the POSIX launcher shim that resolves and runs the CLI."""
    return """#!/usr/bin/env bash
# personetta launcher (generated by install-personetta.sh).
# PATH-independent: runs an installed package if importable, else the source
# tree via PERSONETTA_BASE/src. Keeps `personetta` working on locked-down boxes.
: "${{PERSONETTA_BASE:={base}}}"
export PERSONETTA_BASE

if python3 -c "import generator" >/dev/null 2>&1; then
    exec python3 -m generator "$@"
elif [ -d "$PERSONETTA_BASE/src" ]; then
    exec env PYTHONPATH="$PERSONETTA_BASE/src${{PYTHONPATH:+:$PYTHONPATH}}" \\
        python3 -m generator "$@"
else
    echo "personetta: cannot locate the generator package." >&2
    echo "  Set PERSONETTA_BASE to the repository root (containing src/generator)." >&2
    exit 127
fi
""".format(base=base_dir)
