"""Markdown prompt style generator.

Generates the original verbose markdown format.
Used for backward compatibility and comprehensive documentation.
"""

from __future__ import annotations

import re
from datetime import datetime

from .base import BasePromptStyle


class MarkdownPromptStyle(BasePromptStyle):
    """
    Generates verbose markdown-formatted prompts.

    Includes full documentation with sections, formatting, and compliance footer.
    """

    def __init__(self, merged_role: dict, include_metadata: bool = True):
        """
        Args:
            merged_role: Merged role dictionary
            include_metadata: Whether to include generation metadata comment
        """
        super().__init__(merged_role)
        self.include_metadata = include_metadata

    def generate(self) -> str:
        """Generate the original verbose markdown format."""
        output = []

        # Metadata header (if requested)
        if self.include_metadata:
            output.append(self._generate_metadata_header())
            output.append("\n\n")

        # Opening frame
        output.append(self._generate_opening_frame())
        output.append("\n")

        # Responsibilities
        resp_section = self._format_responsibilities()
        if resp_section:
            output.append(resp_section)
            output.append("\n")

        # Guidelines
        guide_section = self._format_guidelines_imperative()
        if guide_section:
            output.append(guide_section)
            output.append("\n")

        # Tools
        tools_section = self._format_tools_contextual()
        if tools_section:
            output.append(tools_section)
            output.append("\n")

        # Examples
        examples_section = self._format_examples_instructional()
        if examples_section:
            output.append(examples_section)
            output.append("\n")

        # Verification
        verification_section = self._format_verification()
        if verification_section:
            output.append(verification_section)
            output.append("\n")

        # Compliance footer
        output.append(self._generate_compliance_footer())

        return "".join(output)

    def _generate_metadata_header(self) -> str:
        """Generate HTML comment with metadata."""
        recipe_name = self.role.get("_recipe_name", self.role.get("name", "unknown"))
        timestamp = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")

        return f"""<!-- Generated by personetta -->
<!-- Recipe: {recipe_name} -->
<!-- Generated: {timestamp} -->"""

    def _generate_opening_frame(self) -> str:
        """
        Create the opening that establishes the role and primes the AI.

        Structure:
        1. Direct role assignment: "You are now a..."
        2. Core identity: "Your expertise is in..."
        3. Primary objectives: "Your goal is to..."
        4. Scope boundaries: "You focus on X, not Y"
        """
        name = self.role.get("_recipe_name", self.role.get("name", "Specialized Role"))
        description = self.role.get(
            "_recipe_description", self.role.get("description", "")
        )

        output = [f"# Adopting Role: {name}\n"]
        output.append(f"You are now acting as a **{name}**.\n")

        if description:
            output.append(f"{description}\n")

        return "".join(output)

    def _format_responsibilities(self) -> str:
        """Format responsibilities/non_responsibilities as imperative responsibilities."""
        should = self.role.get("responsibilities", [])
        should_not = self.role.get("non_responsibilities", [])

        if not should and not should_not:
            return ""

        output = ["## Your Core Responsibilities\n"]

        if should:
            output.append("**You MUST:**\n")
            for item in should:
                text = self._extract_text_from_item(item)
                transformed = self._apply_imperative_patterns(text)
                output.append(f"- {transformed}\n")
            output.append("\n")

        if should_not:
            output.append("**You MUST NOT:**\n")
            for item in should_not:
                text = self._extract_text_from_item(item)

                # For non_responsibilities, ensure they start with a prohibition
                if not any(
                    text.lower().startswith(word)
                    for word in [
                        "never",
                        "do not",
                        "don't",
                        "must not",
                        "cannot",
                        "avoid",
                    ]
                ):
                    # Prepend "Never" for items not already negative
                    transformed = (
                        f"Never {text.lower()}" if text[0].isupper() else f"Never {text}"
                    )
                else:
                    # Already negative, just apply transformations
                    transformed = self._apply_imperative_patterns(text)
                output.append(f"- {transformed}\n")

        return "".join(output)

    def _format_guidelines_imperative(self) -> str:
        """Transform guidelines from declarative to imperative."""
        guidelines = self.role.get("guidelines", [])

        if not guidelines:
            return ""

        output = ["## How You Work\n"]
        output.append("**Critical guidelines you must follow:**\n\n")

        for idx, guideline in enumerate(guidelines, 1):
            text = self._extract_text_from_item(guideline)
            transformed = self._transform_guideline_to_directive(text)
            output.append(f"{idx}. {transformed}\n\n")

        return "".join(output)

    def _transform_guideline_to_directive(self, guideline: str) -> str:
        """
        Transform a single guideline into an imperative directive.

        Applies multiple transformation patterns and enhancements.
        """
        # Apply basic imperative patterns
        directive = self._apply_imperative_patterns(guideline)

        # Add emphasis if not already present
        if not directive.startswith("**"):
            # Find first sentence or clause, excluding code elements like __init__.py
            # Look for sentence-ending punctuation after at least 10 chars
            match = re.search(r"^(.{10,}?)([.!?](?:\s|$))", directive)
            if match:
                first_part = match.group(1)
                rest = directive[len(first_part) :]
                directive = f"**{first_part}**{rest}"
            else:
                # No clear sentence ending, look for em-dash or semicolon
                for sep in [" — ", " - ", "; "]:
                    if sep in directive:
                        idx = directive.index(sep)
                        first_part = directive[:idx]
                        rest = directive[idx:]
                        directive = f"**{first_part}**{rest}"
                        break
                else:
                    # Bold the whole thing
                    directive = f"**{directive}**"

        return directive

    def _format_tools_contextual(self) -> str:
        """Transform tool list into contextual guidance."""
        tools = self.role.get("tools", [])

        if not tools:
            return ""

        output = ["## Tools at Your Disposal\n"]

        for tool in tools:
            if isinstance(tool, dict):
                name = tool.get("name", "")
                purpose = tool.get("purpose", "")
                when = tool.get("when", "")

                if name and purpose:
                    # Contextual framing - use "when" as the primary context
                    if when:
                        # When clause explains the use case
                        output.append(
                            f"**{name}** — {purpose}\n*When to use: {when}*\n\n"
                        )
                    else:
                        output.append(f"**{name}** — {purpose}\n\n")
            elif isinstance(tool, str):
                output.append(f"- {tool}\n")

        return "".join(output)

    def _format_examples_instructional(self) -> str:
        """Transform examples into instructional demonstrations."""
        examples = self.role.get("examples", [])

        if not examples:
            return ""

        output = ["## What Quality Looks Like\n"]
        output.append("Here are examples of the kind of work you do:\n\n")

        for example in examples:
            if isinstance(example, dict):
                scenario = example.get("scenario", "")
                input_text = example.get("input", "")
                output_text = example.get("output", "")

                if scenario:
                    output.append(f"**Scenario:** {scenario}\n\n")
                if input_text:
                    output.append(f"**Input:** {input_text}\n\n")
                if output_text:
                    output.append(f"**Your response:** {output_text}\n\n")

                output.append("---\n\n")
            elif isinstance(example, str):
                output.append(f"{example}\n\n")

        return "".join(output)

    def _format_verification(self) -> str:
        """Format verification checklist as actionable items."""
        verification = self.role.get("verification", [])

        if not verification:
            return ""

        output = ["## Verification\n"]
        output.append("After completing work, you must:\n")

        for item in verification:
            # Handle dict (with 'check' key) or string
            if isinstance(item, dict):
                check_text = item.get("check", str(item))
            elif isinstance(item, str):
                check_text = item
            else:
                check_text = str(item)

            # Transform to imperative if needed
            transformed = self._apply_imperative_patterns(check_text)
            output.append(f"- {transformed}\n")

        return "".join(output)

    def _generate_compliance_footer(self) -> str:
        """Generate compliance reporting instructions."""
        return """---

## After Completing Work

When you finish a task, provide a brief compliance report:

1. **Verification**: State which verification checks passed
2. **Guidelines Applied**: List 3-5 guidelines you actively followed
3. **Deviations**: Note any guidelines you chose not to follow and why

This helps validate that you're operating correctly within this role.

---

**Ready to begin.** Confirm you understand this role and ask for the first task."""
